### ISSUE TITLE
compiling failure on ubuntu 16.04 opencv3.4

### ISSUE THREAD

**Issue by yunbiaolin** [omricarmi/FastHEVC#5]
Hi,

when i trying to build this project, it has below link issue.  do u meet this issue before?

CMakeFiles/HM_16_14_DEC.dir/source/Lib/TLibEncoder/TEncGOP.cpp.o: In function `c                                                                                                             v::Mat::Mat(int, int, int, cv::Scalar_<double> const&)':
TEncGOP.cpp:(.text._ZN2cv3MatC2EiiiRKNS_7Scalar_IdEE[_ZN2cv3MatC5EiiiRKNS_7Scala                                                                                                             r_IdEE]+0xe0): undefined reference to `cv::Mat::operator=(cv::Scalar_<double> co                                                                                                             nst&)'
CMakeFiles/HM_16_14_DEC.dir/source/Lib/TLibEncoder/TEncGOP.cpp.o: In function `c                                                                                                             v::Mat::Mat(cv::Mat const&)':
TEncGOP.cpp:(.text._ZN2cv3MatC2ERKS0_[_ZN2cv3MatC5ERKS0_]+0x182): undefined refe                                                                                                             rence to `cv::Mat::copySize(cv::Mat const&)'
CMakeFiles/HM_16_14_DEC.dir/source/Lib/TLibEncoder/TEncGOP.cpp.o: In function `c                                                                                                             v::Mat::~Mat()':
TEncGOP.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x39): undefined reference to                                                                                                              `cv::fastFree(void*)'

**Comment by omricarmi** [comment]
I fixed the problem you can try it now.
let me know if it works for you :-)

**Comment by omricarmi** [comment]
@yunbiaolin I fixed the problem you can try it now.
let me know if it works for you :-)
moreover, notice that the main propose of the project is the Encoder.
so to build the encoder you need to change your make target to HM_16_14_ENC.
